In [6]:
%load_ext autoreload
%autoreload 2

In [38]:
import pandas as pd
import numpy as np
import matplotlib
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from util import DenseTransformer
from sklearn.metrics import classification_report
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score, recall_score, roc_auc_score, roc_curve
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, KFold
from sklearn.svm import SVC

In [4]:
df = pd.read_csv('./data/dataset_with_content.csv', index_col=0, parse_dates=True)

In [5]:
df.head()

l      close  \
next_day                                                              
2006-01-11  /newsevents/pressreleases/bcreg20060110a.htm  1294.1801   
2006-02-03  /newsevents/pressreleases/bcreg20060203a.htm  1264.0300   
2006-02-06  /newsevents/pressreleases/bcreg20060206a.htm  1265.0200   
2006-02-17  /newsevents/pressreleases/bcreg20060217a.htm  1287.2400   
2006-02-24  /newsevents/pressreleases/bcreg20060224a.htm  1289.4301   

                                d                 date  pct_change  \
next_day                                                             
2006-01-11  1/10/2006 10:00:00 AM  2006-01-10 10:00:00    0.006314   
2006-02-03               2/3/2006  2006-02-03 00:00:00   -0.000783   
2006-02-06               2/6/2006  2006-02-06 00:00:00    0.008161   
2006-02-17              2/17/2006  2006-02-17 00:00:00    0.003281   
2006-02-24              2/24/2006  2006-02-24 00:00:00   -0.003624   

                                                pt  \
next_day                                             
2006-01-11  Banking and Consumer Regulatory Policy   
2006-02-03  Banking and Consumer Regulatory Policy   
2006-02-06  Banking and Consumer Regulatory Policy   
2006-02-17  Banking and Consumer Regulatory Policy   
2006-02-24  Banking and Consumer Regulatory Policy   

                                                            t  \
next_day                                                        
2006-01-11  Federal Bank and Thrift Agencies Propose Guida...   
2006-02-03  Federal Financial Regulatory Agencies Issue In...   
2006-02-06  Approval of final rule on risk-based capital t...   
2006-02-17  Federal Financial Regulatory Agencies Extend C...   
2006-02-24  Federal Regulators Release Summary Findings of...   

                                                      content  
next_day                                                       
2006-01-11  \nThe federal bank and thrift regulatory agenc...  
2006-02-03  \nThe federal financial regulatory agencies to...  
2006-02-06  \nThe Federal Reserve Board on Monday announce...  
2006-02-17  \nThe federal financial regulatory agencies to...  
2006-02-24  \nWASHINGTON, D.C. - The federal bank and thri...

In [24]:
df.content = df.content.fillna('')

In [25]:
X = df.t +'\n'+ df.content
y = df['pct_change'] > 0

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [29]:
def evaluate_model(model, X=X_train, y=y_train):
    text_svm = make_pipeline(
        CountVectorizer(),
        TfidfTransformer(),
        DenseTransformer(),
        model
    )
    kf = KFold(n_splits=5)
    for train_idx, test_idx in kf.split(X):
    
    scores = cross_val_score(text_svm, X, y, cv=5)#n_jobs=-1)
    print()
    return scores

In [32]:
evaluate_model(GaussianNB())

[0.48221344 0.52173913 0.50988142 0.53359684 0.47920792]


array([0.48221344, 0.52173913, 0.50988142, 0.53359684, 0.47920792])

In [33]:
evaluate_model(SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, random_state=42, max_iter=5, tol=None))

[0.55335968 0.54347826 0.52371542 0.52766798 0.51089109]


array([0.55335968, 0.54347826, 0.52371542, 0.52766798, 0.51089109])

In [36]:
evaluate_model(SVC(random_state=42))

/home/harinsa/miniconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/harinsa/miniconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/harinsa/miniconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/harinsa/miniconda3/lib/python3.7/site-packa

[0.54150198 0.54150198 0.54150198 0.54150198 0.54257426]


array([0.54150198, 0.54150198, 0.54150198, 0.54150198, 0.54257426])

In [57]:
recall_score(y, y_pred)

0.9908913467794405

In [62]:
text_clf = make_pipeline(
    CountVectorizer(),
    TfidfTransformer(),
    SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, random_state=42, max_iter=5, tol=None)
)

In [80]:
cross_val_score(text_clf, X_train, y_train, cv=5)

array([0.50592885, 0.53754941, 0.53557312, 0.5513834 , 0.52277228])

In [102]:
cross_val_score(text_nb_clf, X_train, y_train, cv=5)

array([0.47035573, 0.46640316, 0.46837945, 0.48418972, 0.52079208])

In [104]:

text_svm = make_pipeline(
    CountVectorizer(),
    TfidfTransformer(),
    SVC(random_state=42)
)

In [105]:
cross_val_score(text_svm, X_train, y_train, cv=5)

/home/harinsa/miniconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


array([0.54743083, 0.54743083, 0.54743083, 0.54743083, 0.54851485])

In [115]:
grid = evaluate_model(SVC(random_state=42))

/home/harinsa/miniconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [117]:
grid.cv_results_

/home/harinsa/miniconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/harinsa/miniconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/harinsa/miniconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/harinsa/miniconda3/

{'mean_fit_time': array([16.94346161]),
 'std_fit_time': array([1.56041995]),
 'mean_score_time': array([4.33206258]),
 'std_score_time': array([0.06780955]),
 'params': [{}],
 'split0_test_score': array([0.54743083]),
 'split1_test_score': array([0.54743083]),
 'split2_test_score': array([0.54743083]),
 'split3_test_score': array([0.54743083]),
 'split4_test_score': array([0.54851485]),
 'mean_test_score': array([0.54764729]),
 'std_test_score': array([0.00043335]),
 'rank_test_score': array([1], dtype=int32),
 'split0_train_score': array([0.54770143]),
 'split1_train_score': array([0.54770143]),
 'split2_train_score': array([0.54770143]),
 'split3_train_score': array([0.54770143]),
 'split4_train_score': array([0.54743083]),
 'mean_train_score': array([0.54764731]),
 'std_train_score': array([0.00010824])}